version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: live_broadcast_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/live_broadcast_db
      JWT_SECRET: your_secret_key
    depends_on:
      - db
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    command: ["nginx", "-g", "daemon off;"]

volumes:
  postgres_data: